# Generated by Django 5.1.6 on 2025-05-04 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="tg_chat_id",
            field=models.CharField(
                blank=True,
                help_text="Tелеграм чат ID",
                max_length=100,
                null=True,
                verbose_name="Tелеграм чат ID",
            ),
        ),
    ]
